// import { ThemeProvider } from "@/context/ThemeProvider";
import 'tailwindcss/tailwind.css'
import "./globals.css";
import { Inter } from "next/font/google";
import WeatherDataProvider from "@/context/WeatherDataProvider";
import { Toaster } from "sonner";
import NavBar from "@/components/NavBar";
import ThemeProvider from "@/context/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-100/75 dark:bg-black/50 `}>
        <WeatherDataProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            disableTransitionOnChange
          >
            <Toaster richColors />
            <div className="px-2 md:px-6 lg:px-10 max-w-screen-2xl m-auto transition-colors duration-1000  ">
              <NavBar />
              {children}
            </div>
          </ThemeProvider>
        </WeatherDataProvider>
      </body>
    </html>
  );
}
